/**
 * Timezone to Country Mapping
 * Maps IANA timezone identifiers to ISO 3166-1 alpha-2 country codes
 * Used as fallback when IP-based geo detection fails
 */

const timezoneToCountryMap: Record<string, string> = {
  // Americas
  'America/New_York': 'US',
  'America/Chicago': 'US',
  'America/Denver': 'US',
  'America/Los_Angeles': 'US',
  'America/Phoenix': 'US',
  'America/Anchorage': 'US',
  'America/Adak': 'US',
  'America/Honolulu': 'US',
  'America/Toronto': 'CA',
  'America/Vancouver': 'CA',
  'America/Winnipeg': 'CA',
  'America/Halifax': 'CA',
  'America/St_Johns': 'CA',
  'America/Mexico_City': 'MX',
  'America/Cancun': 'MX',
  'America/Merida': 'MX',
  'America/Monterrey': 'MX',
  'America/Mazatlan': 'MX',
  'America/Chihuahua': 'MX',
  'America/Hermosillo': 'MX',
  'America/Tijuana': 'MX',
  'America/Sao_Paulo': 'BR',
  'America/Rio_Branco': 'BR',
  'America/Manaus': 'BR',
  'America/Cuiaba': 'BR',
  'America/Campo_Grande': 'BR',
  'America/Belem': 'BR',
  'America/Fortaleza': 'BR',
  'America/Recife': 'BR',
  'America/Araguaina': 'BR',
  'America/Maceio': 'BR',
  'America/Bahia': 'BR',
  'America/Santarem': 'BR',
  'America/Porto_Velho': 'BR',
  'America/Boa_Vista': 'BR',
  'America/Noronha': 'BR',
  'America/Buenos_Aires': 'AR',
  'America/Cordoba': 'AR',
  'America/Mendoza': 'AR',
  'America/Rosario': 'AR',
  'America/Jujuy': 'AR',
  'America/Catamarca': 'AR',
  'America/ComodRivadavia': 'AR',
  'America/Rio_Gallegos': 'AR',
  'America/Ushuaia': 'AR',
  'America/Santiago': 'CL',
  'America/Punta_Arenas': 'CL',
  'America/EasterIsland': 'CL',
  'America/Lima': 'PE',
  'America/Bogota': 'CO',
  'America/Caracas': 'VE',
  'America/Maracaibo': 'VE',
  'America/La_Paz': 'BO',
  'America/Asuncion': 'PY',
  'America/Montevideo': 'UY',
  'America/Guayaquil': 'EC',
  'America/Galapagos': 'EC',
  'America/Paramaribo': 'SR',
  'America/Cayenne': 'GF',
  'America/Guyana': 'GY',
  'America/Georgetown': 'GY',
  'America/Havana': 'CU',
  'America/Jamaica': 'JM',
  'America/Montego_Bay': 'JM',
  'America/Port-au-Prince': 'HT',
  'America/Santo_Domingo': 'DO',
  'America/Puerto_Rico': 'PR',
  'America/Guatemala': 'GT',
  'America/Belize': 'BZ',
  'America/Tegucigalpa': 'HN',
  'America/Managua': 'NI',
  'America/San_Jose': 'CR',
  'America/Costa_Rica': 'CR',
  'America/Nicaragua': 'NI',
  'America/Panama': 'PA',
  'America/El_Salvador': 'SV',
  'America/Martinique': 'MQ',
  'America/Barbados': 'BB',
  'America/St_Lucia': 'LC',
  'America/St_Vincent': 'VC',
  'America/Grenada': 'GD',
  'America/Port_of_Spain': 'TT',
  'America/Aruba': 'AW',
  'America/Curacao': 'CW',
  'America/Kralendijk': 'BQ',
  'America/Lower_Princes': 'SX',
  'America/Marigot': 'MF',
  'America/St_Barthelemy': 'BL',
  'America/Anguilla': 'AI',
  'America/Montserrat': 'MS',
  'America/Dominica': 'DM',
  'America/Antigua': 'AG',
  'America/St_Kitts': 'KN',
  'America/Nassau': 'BS',
  'America/Cayman': 'KY',
  'America/Turks_and_Caicos': 'TC',
  // Europe
  'Europe/London': 'GB',
  'Europe/Dublin': 'IE',
  'Europe/Paris': 'FR',
  'Europe/Berlin': 'DE',
  'Europe/Munich': 'DE',
  'Europe/Frankfurt': 'DE',
  'Europe/Rome': 'IT',
  'Europe/Milan': 'IT',
  'Europe/Madrid': 'ES',
  'Europe/Barcelona': 'ES',
  'Europe/Amsterdam': 'NL',
  'Europe/Brussels': 'BE',
  'Europe/Vienna': 'AT',
  'Europe/Zurich': 'CH',
  'Europe/Stockholm': 'SE',
  'Europe/Oslo': 'NO',
  'Europe/Copenhagen': 'DK',
  'Europe/Helsinki': 'FI',
  'Europe/Warsaw': 'PL',
  'Europe/Prague': 'CZ',
  'Europe/Budapest': 'HU',
  'Europe/Bucharest': 'RO',
  'Europe/Sofia': 'BG',
  'Europe/Athens': 'GR',
  'Europe/Lisbon': 'PT',
  'Europe/Moscow': 'RU',
  'Europe/Kiev': 'UA',
  'Europe/Minsk': 'BY',
  'Europe/Riga': 'LV',
  'Europe/Tallinn': 'EE',
  'Europe/Vilnius': 'LT',
  'Europe/Istanbul': 'TR',
  // Asia
  'Asia/Jerusalem': 'IL',
  'Asia/Tel_Aviv': 'IL',
  'Asia/Dubai': 'AE',
  'Asia/Kuwait': 'KW',
  'Asia/Bahrain': 'BH',
  'Asia/Qatar': 'QA',
  'Asia/Riyadh': 'SA',
  'Asia/Muscat': 'OM',
  'Asia/Tehran': 'IR',
  'Asia/Baghdad': 'IQ',
  'Asia/Damascus': 'SY',
  'Asia/Beirut': 'LB',
  'Asia/Amman': 'JO',
  'Asia/Tokyo': 'JP',
  'Asia/Seoul': 'KR',
  'Asia/Pyongyang': 'KP',
  'Asia/Shanghai': 'CN',
  'Asia/Beijing': 'CN',
  'Asia/Chongqing': 'CN',
  'Asia/Harbin': 'CN',
  'Asia/Urumqi': 'CN',
  'Asia/Kashgar': 'CN',
  'Asia/Hong_Kong': 'HK',
  'Asia/Macau': 'MO',
  'Asia/Taipei': 'TW',
  'Asia/Singapore': 'SG',
  'Asia/Bangkok': 'TH',
  'Asia/Jakarta': 'ID',
  'Asia/Manila': 'PH',
  'Asia/Kuala_Lumpur': 'MY',
  'Asia/Ho_Chi_Minh': 'VN',
  'Asia/Hanoi': 'VN',
  'Asia/Yangon': 'MM',
  'Asia/Dhaka': 'BD',
  'Asia/Kolkata': 'IN',
  'Asia/Karachi': 'PK',
  'Asia/Kabul': 'AF',
  'Asia/Tashkent': 'UZ',
  'Asia/Almaty': 'KZ',
  'Asia/Bishkek': 'KG',
  'Asia/Dushanbe': 'TJ',
  'Asia/Ashgabat': 'TM',
  'Asia/Yerevan': 'AM',
  'Asia/Tbilisi': 'GE',
  'Asia/Baku': 'AZ',
  'Asia/Yekaterinburg': 'RU',
  'Asia/Omsk': 'RU',
  'Asia/Krasnoyarsk': 'RU',
  'Asia/Irkutsk': 'RU',
  'Asia/Yakutsk': 'RU',
  'Asia/Vladivostok': 'RU',
  'Asia/Magadan': 'RU',
  'Asia/Kamchatka': 'RU',
  'Asia/Anadyr': 'RU',
  'Asia/Sakhalin': 'RU',
  'Asia/Ust-Nera': 'RU',
  'Asia/Chita': 'RU',
  'Asia/Khandyga': 'RU',
  'Asia/Ulaanbaatar': 'MN',
  'Asia/Hovd': 'MN',
  'Asia/Choibalsan': 'MN',
  // Africa
  'Africa/Cairo': 'EG',
  'Africa/Johannesburg': 'ZA',
  'Africa/Lagos': 'NG',
  'Africa/Nairobi': 'KE',
  'Africa/Casablanca': 'MA',
  'Africa/Algiers': 'DZ',
  'Africa/Tunis': 'TN',
  'Africa/Tripoli': 'LY',
  'Africa/Khartoum': 'SD',
  'Africa/Addis_Ababa': 'ET',
  'Africa/Dar_es_Salaam': 'TZ',
  'Africa/Kampala': 'UG',
  'Africa/Kigali': 'RW',
  'Africa/Bujumbura': 'BI',
  'Africa/Djibouti': 'DJ',
  'Africa/Asmara': 'ER',
  'Africa/Mogadishu': 'SO',
  // Oceania
  'Pacific/Auckland': 'NZ',
  'Pacific/Chatham': 'NZ',
  'Australia/Sydney': 'AU',
  'Australia/Melbourne': 'AU',
  'Australia/Brisbane': 'AU',
  'Australia/Adelaide': 'AU',
  'Australia/Perth': 'AU',
  'Australia/Darwin': 'AU',
  'Australia/Hobart': 'AU',
  'Pacific/Honolulu': 'US',
  'Pacific/Guam': 'GU',
  'Pacific/Samoa': 'WS',
  'Pacific/Fiji': 'FJ',
  'Pacific/Tahiti': 'PF',
};

/**
 * Get country code from timezone
 * @param timezone IANA timezone identifier (e.g., "Asia/Jerusalem")
 * @returns ISO 3166-1 alpha-2 country code or null
 */
export function getCountryFromTimezone(timezone: string): string | null {
  return timezoneToCountryMap[timezone] || null;
}

/**
 * Extract country code from language code
 * @param lang Language code (e.g., "he-IL", "en-US")
 * @returns ISO 3166-1 alpha-2 country code or null
 */
export function getCountryFromLanguage(lang: string): string | null {
  const parts = lang.split('-');
  if (parts.length >= 2) {
    const lastPart = parts[parts.length - 1];
    return lastPart ? lastPart.toUpperCase() : null;
  }
  return null;
}
